routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PersonajeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('inicio');

// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

// Perfil de usuario
Route::get('/perfil/{usuario}', [UserController::class, 'show'])->name('user.profile');
Route::get('/perfil/{usuario}/edit', [UserController::class, 'edit'])->name('user.edit');
Route::put('/perfil/{usuario}/edit', [UserController::class, 'update'])->name('user.update');


// Ruta para los personajes
Route::resource('personajes', PersonajeController::class);

// Rutas para los materiales
Route::get('/materiales', [PersonajeController::class, 'listadoMateriales'])->name('personajes.listadomateriales');
Route::get('/materiales/create', [PersonajeController::class, 'createMaterial'])->name('personajes.creatematerial')->middleware('auth.admin');
Route::post('/materiales/create', [PersonajeController::class, 'storeMaterial'])->name('personajes.storematerial')->middleware('auth.admin');
Route::get('/listarmateriales/{material}', [PersonajeController::class, 'showMaterial'])->name('personajes.showmaterial');
Route::get('/listarmateriales/{material}/edit', [PersonajeController::class, 'editMaterial'])->name('personajes.editmaterial')->middleware('auth.admin');
Route::put('/listarmateriales/{material}/edit', [PersonajeController::class, 'updateMaterial'])->name('personajes.updatematerial')->middleware('auth.admin');
Route::delete('/listarmateriales/{material}/edit', [PersonajeController::class, 'destroyMaterial'])->name('personajes.destroymaterial')->middleware('auth.admin');

// Rutas para las ascensiones
Route::get('/ascensiones', [PersonajeController::class, 'listadoAscensiones'])->name('personajes.listadoascensiones');
Route::get('/ascensiones/create', [PersonajeController::class, 'createAscension'])->name('personajes.createascension')->middleware('auth.admin');
Route::post('/ascensiones/create', [PersonajeController::class, 'storeAscension'])->name('personajes.storeascension')->middleware('auth.admin');
Route::get('/listarascensiones/{ascension}/edit', [PersonajeController::class, 'editAscension'])->name('personajes.editascension')->middleware('auth.admin');
Route::put('/listarascensiones/{ascension}/edit', [PersonajeController::class, 'updateAscension'])->name('personajes.updateascension')->middleware('auth.admin');
Route::delete('/listarascensiones/{ascension}/edit', [PersonajeController::class, 'destroyAscension'])->name('personajes.destroyascension')->middleware('auth.admin');

// Ruta para las noticias y sus comentarios
Route::resource('noticias', PostController::class);
Route::post('/comentario/store', [CommentController::class, 'store'])->name('comentario.store');
Route::post('/respuesta/store', [CommentController::class, 'replyStore'])->name('respuesta.store');
Route::delete('/comentario/destroy/{comentario}', [CommentController::class, 'destroy'])->name('comentario.destroy');

resources/views/noticias/_comentarios.blade.php
<div class="container">
   <!-- Formulario para comentar, los usuarios anónimos no podrán comentar -->
 <div class="formComentario">
    @guest
        <center><p style="font-style:italic"><a href="{{ route('login') }}">Inicia sesión</a> para poder comentar.</p></center>
    @endguest
    
    @auth
      <center><h3 style="font-size: 20px; margin: 20px;">¡Déjanos tu comentario!</h3></center>
      
          <form action="{{ route('comentario.store') }}" method="post">
            <input type="hidden" name="noticia_id" value="{{ $noticia->id }}">
          <textarea class="form-control" name="texto" id="texto" rows="5" cols="50"  placeholder="Comparte lo que piensas"></textarea>
          @csrf
            <div style="text-align: right; margin-top: 10px;">
                <input type="submit" class="btnResponder" value="Publicar comentario" />
            </div>
        </form>
    </li>
    @endauth
  </div>

  <h2 style="font-size:22px; border: 1px solid black; border-radius: 10px; padding: 10px; margin-bottom: 20px;">Todos los comentarios</h2>

  <!-- Lista de comentarios -->
  @foreach($noticia->comments as $comentario)
    <div class="comentario">
      <div class="cabeceraComentario">
      <div style="width:32px; height:32px;border-radius:50%;overflow:hidden; display:inline"><img src='/storage/{{$comentario->user->profile_photo_path}}' style="width:32px" /></div> <a style="margin-left:10px; margin-right:10px; text-decoration:none;" href="{{ route('user.profile', $comentario->user->id ) }}" role="button" aria-haspopup="true" aria-expanded="false"> {{$comentario->user->name}}  </a><span style="font-size: 14px; font-style:italic;">el <?php echo date("d/m/Y", strtotime($comentario->created_at))  ?></span> @auth @if (auth()->user()->role == "admin")<button type="button" class="btn" data-toggle="modal" data-target="#ModalBorrarComentario" title="Eliminar este comentario."  style="margin-left: 10px;"><i class="fas fa-trash"></i></button>@endif @endauth
        
            <!-- Modal para borrar un comentario -->
            <div class="modal fade" id="ModalBorrarComentario" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Borrar</h5>
                    </button>
                  </div>
                  <div class="modal-body">
                    ¿Desea realmente borrar este comentario? 
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <form action="{{ route('comentario.destroy',$comentario) }}" method="post">@csrf @method('DELETE') <input type="submit" class="btn btn-danger" value="Borrar" /> </form>      </div>
                </div>
              </div>
            </div>
      </div>
      <div class="cuerpoComentario">
        {{$comentario->texto}}
       
      </div>
        @foreach($comentario->answers as $respuesta)
        <hr/>
        <div class="comentario" style="margin-left: 20px;">
          <div class="cabeceraComentario">
          <div style="width:32px; height:32px;border-radius:50%;overflow:hidden; display:inline"><img src='/storage/{{$respuesta->user->profile_photo_path}}' style="width:32px" /></div> <a style="margin-left:10px; margin-right:10px; text-decoration:none;" href="{{ route('user.profile', $respuesta->user->id ) }}" role="button" aria-haspopup="true" aria-expanded="false"> {{$respuesta->user->name}}  </a><span style="font-size: 14px; font-style:italic;">el <?php echo date("d/m/Y", strtotime($respuesta->created_at))  ?></span> @auth @if (auth()->user()->role == "admin")<button type="button" class="btn" data-toggle="modal" data-target="#ModalBorrarRespuesta" title="Eliminar este comentario."  style="margin-left: 10px;"><i class="fas fa-trash"></i></button>@endif @endauth
        

            <div class="modal fade" id="ModalBorrarRespuesta" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Borrar</h5>
        </button>
      </div>
      <div class="modal-body">
        ¿Desea realmente borrar esta respuesta?  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <form action="{{ route('comentario.destroy',$respuesta) }}" method="post">@csrf @method('DELETE') <input type="submit" class="btn btn-danger" value="Borrar" /> </form>      </div>
    </div>
  </div>
</div>
          </div>
          <div class="cuerpoComentario">
            <div>{{ $respuesta->texto }}</div>
            
          </div>
          
    </div>

    <!-- Modal para borrar la respuesta de un comentario -->


        
        @endforeach
        
        <!-- Responder un comentario -->
        @guest
    @endguest
    @auth
         <form action="{{ route('respuesta.store') }}" method="post" style="margin-top: 10px;">
            <input type="hidden" name="noticia_id" value="{{ $noticia->id }}">
            <input type="hidden" name="comentario_id" value="{{ $comentario->id }}">
          <textarea class="form-control" name="texto" id="texto" rows="3" cols="20" placeholder="Continuar esta conversación"></textarea>
          @csrf
            <div style="text-align: right; margin-top: 10px;">
                <input type="submit" class="btnResponder" value="Responder" />
            </div>
        </form>
      @endauth
    </div>



  @endforeach

  

resources/views/noticias/_form.blade.php
@csrf
<table class="table">
    <tr>
        <td><label for="nombre" class="form-label">Nombre de la noticia:</label></td>
        <td>
            <input type="text" class="form-control" id="nombre" name="nombre" value="{{ old('nombre',$noticia->nombre) }}" maxlength="100">
            @error('nombre')
            <small class='alert alert-danger'>{{ $message }}</small>
            @enderror
        </td>
    </tr>
    <tr class="mb-3">
        <td><label for="imagen" class="form-label">Imagen:</label> </td>
        <td>
            <i>Nueva imagen:</i><br/> <input type="file" class="form-control mb-3" id="imagen" name="imagen" value="{{ old('imagen',$noticia->imagen) }}" maxlength="150">
            @if (old('imagen',$noticia->imagen)) <!-- Si existe imagen anterior, se muestra  -->
                <i >Imagen anterior:</i><br/> <img style="margin-bottom:10px;" src='{{ URL::asset("storage/$noticia->imagen") }}' HEIGHT="100px" /> 
            @endif
            @if ($errors->has('imagen'))
            <small class='alert alert-danger'>{{ $errors->first('imagen') }}</small>
            @endif
        </td>
    </tr>
    <tr class="mt-3">
        <td><label for="resumen" class="form-label">Resumen:</label><br></td>
        <td>
            <textarea class="form-control" name="resumen" id="resumen" rows="5" cols="50">{{ old('resumen',$noticia->resumen) }}</textarea>
            @error('resumen')
            <small class='alert alert-danger'>{{ $message }}</small>
            @enderror
        </td>
    </tr>
    <tr>
        <td><label for="texto" class="form-label">Texto:</label><br></td>
        <td>
            <textarea class="form-control" name="texto" id="texto" rows="10" cols="50">{{ old('texto',$noticia->texto) }}</textarea>
            @error('texto')
            <small class='alert alert-danger'>{{ $message }}</small>
            @enderror
        </td>
    </tr>
</table>


<script>
    CKEDITOR.replace('texto', {
   removeButtons: 'Source',
    // The rest of options...
} );
</script>

resources/views/noticias/create.blade.php
@extends('plantillas.master')

@section('title')
Creación de noticia
@stop

@section('central')
<h2>CREACIÓN DE NOTICIA</h2>
<form action="{{ route('noticias.store') }}" method="post" enctype="multipart/form-data">
    @include('noticias._form')
    <div style="text-align: right; margin-top: 10px;">
        <a class="btn btn-secondary" href="{{ route('noticias.index') }}">Cancelar</a>
        <input type="reset" class="btn btn-danger" name="Limpiar" />
        <input type="submit" class="btn btn-success" value="Crear noticia" />
    </div>
</form>



@stop

resources/views/noticias/edit.blade.php
@extends('plantillas.master')

@section('title')
Edición de noticia
@stop

@section('central')
<h2>EDICIÓN DE NOTICIA</h2>

<form action="{{ route('noticias.update', $noticia->id) }}" method="post" enctype="multipart/form-data">
    @METHOD('PUT')
    @include('noticias._form')
    <div style="text-align: right; margin-top: 10px;">
        <a class="btn btn-secondary" href="{{ route('noticias.show', $noticia) }}">Cancelar</a>
        <input type="reset" class="btn btn-danger" name="Limpiar" />
        <input type="submit" class="btn btn-success" value="Guardar cambios" />
    </div>
</form>
@stop

resources/views/noticias/index.blade.php
@extends('plantillas.master')

@section('title')
Noticias
@stop

@section('central')
<div class="info">
    <h2>Noticias</h2>
    <div>Todas las noticias más recientes.</div>
</div>

<!-- Si el usuario está registrado y es admin... -->
@auth
    @if (auth()->user()->role == "admin")
        <div class="btnDerecha">
            <a class="btn btn-secondary " href="{{ route('noticias.create') }}" title="Crear nueva noticia."><i class="fas fa-plus-circle"></i></a>
        </div>
    @endif
@endauth
<style>
    .divNoticia{
        padding: 10px;
        margin-bottom: 5px;
        background-color: #e9cbcb;
        border-radius: 10px;
    }

    .divNoticia:hover{
        background-color: #e9aeae;
        cursor:pointer;
    }

</style>

<!-- Lista de noticias -->
@foreach($noticias as $noticia)
    <div class="container">
        <div class="row divNoticia" onclick="window.location.href='{{ route('noticias.show',$noticia) }}'">
            <div class="text-center col" style="margin-top:2px;"><center><img style="max-height: 100px;" src='{{ URL::asset("storage/$noticia->imagen") }}'  /></center></div>
            <div class="col-12 col-md-8">
                <div class="row">
                    <div class="row d-flex flex-row bd-highlight ">
                        <div class="col-12" style="font-size: 20px; padding:10px;">{{ $noticia->nombre }}</div>
                    </div>
                    <div class="row d-flex flex-row bd-highlight">
                        <div class="col-12" style="font-size: 12px; padding:10px;">{{ $noticia->resumen }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endforeach
    

{!! $noticias->links() !!}





@stop

resources/views/noticias/noticia.blade.php
@extends('plantillas.master')

@section('title')
{{ $noticia->nombre }}
@stop

@section('central')

<!-- Se o usuario está rexistrado e é admin móstranse opcións -->
@auth
  @if (auth()->user()->role == "admin")
    <div class="btnDerecha">
    <a href="{{ route('noticias.edit',$noticia) }}" class="btn btn-warning" title="Editar esta noticia."><i class="fas fa-edit"></i></a> 
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#ModalBorrar" title="Borrar esta noticia."><i class="fas fa-trash"></i></button>
    </div>
  @endif
@endauth
<style>
  .volver{
    background-color: #fba4a4;
    display: flex;
  align-items: center;
    text-align: center;
    border-radius: 10px;
    color:white;
    margin-top: 50px;
  }

  .volver:hover{
    cursor:pointer;
    background-color: #f96767;
  }

  .volver a{
    text-decoration: none;
    color: white;
    display:block;
    padding: 20px;
  }

  .comentario{
    background-color: #dddddd;
    border-radius: 10px;
    padding: 10px;
    margin-top: 10px;
  }

  .cabeceraComentario{
    font-size: 20px;
    display: flex;
    align-items: center;
  }

  .cuerpoComentario{
    margin-top: 10px;
  }

  .formComentario{
    margin-bottom: 20px;

  }

  .btnResponder {
    background-color: #00c900;
    border-radius: 5px;
    color: white;
    border: none;
  }

  .btnResponder:hover {
    background-color: #039903;
  }
</style>
<!-- Cuerpo de la noticia -->
<div class="container mb-5">
    <h1 style="margin-top:50px;">{{ $noticia->nombre }}</h1>
    <div style="margin-top: 10px; font-size: 18px; font-style: italic;">{{ $noticia->resumen }}</div>
    <p style="font-size: 12px; text-align: right;">Publicado el {{$noticia->updated_at->format('d/m/y')}}

    <center><img src='{{ URL::asset("storage/$noticia->imagen") }}' width="100%" /></center>
    <div class="pt-5">{!! $noticia->texto !!}</div>
</div>

<!-- <div class="d-flex justify-content-center">
  <div class="volver"><a href='{{  route('noticias.index')  }}'>Volver a la lista de noticias</a></div>
</div> -->

<hr>

<!-- Región de comentarios -->
@include('noticias._comentarios')

<!-- Modal para borrar una noticia -->
<div class="modal fade" id="ModalBorrar" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Borrar</h5>
        </button>
      </div>
      <div class="modal-body">
        ¿Desea realmente borrar esta noticia?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <form action="{{ route('noticias.destroy',$noticia) }}" method="post">@csrf @method('DELETE') <input type="submit" class="btn btn-danger" value="Borrar" /> </form>      </div>
    </div>
  </div>
</div>


@stop