routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PersonajeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('inicio');

// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

// Perfil de usuario
Route::get('/perfil/{usuario}', [UserController::class, 'show'])->name('user.profile');
Route::get('/perfil/{usuario}/edit', [UserController::class, 'edit'])->name('user.edit');
Route::put('/perfil/{usuario}/edit', [UserController::class, 'update'])->name('user.update');


// Ruta para los personajes
Route::resource('personajes', PersonajeController::class);

// Rutas para los materiales
Route::get('/materiales', [PersonajeController::class, 'listadoMateriales'])->name('personajes.listadomateriales');
Route::get('/materiales/create', [PersonajeController::class, 'createMaterial'])->name('personajes.creatematerial')->middleware('auth.admin');
Route::post('/materiales/create', [PersonajeController::class, 'storeMaterial'])->name('personajes.storematerial')->middleware('auth.admin');
Route::get('/listarmateriales/{material}', [PersonajeController::class, 'showMaterial'])->name('personajes.showmaterial');
Route::get('/listarmateriales/{material}/edit', [PersonajeController::class, 'editMaterial'])->name('personajes.editmaterial')->middleware('auth.admin');
Route::put('/listarmateriales/{material}/edit', [PersonajeController::class, 'updateMaterial'])->name('personajes.updatematerial')->middleware('auth.admin');
Route::delete('/listarmateriales/{material}/edit', [PersonajeController::class, 'destroyMaterial'])->name('personajes.destroymaterial')->middleware('auth.admin');

// Rutas para las ascensiones
Route::get('/ascensiones', [PersonajeController::class, 'listadoAscensiones'])->name('personajes.listadoascensiones');
Route::get('/ascensiones/create', [PersonajeController::class, 'createAscension'])->name('personajes.createascension')->middleware('auth.admin');
Route::post('/ascensiones/create', [PersonajeController::class, 'storeAscension'])->name('personajes.storeascension')->middleware('auth.admin');
Route::get('/listarascensiones/{ascension}/edit', [PersonajeController::class, 'editAscension'])->name('personajes.editascension')->middleware('auth.admin');
Route::put('/listarascensiones/{ascension}/edit', [PersonajeController::class, 'updateAscension'])->name('personajes.updateascension')->middleware('auth.admin');
Route::delete('/listarascensiones/{ascension}/edit', [PersonajeController::class, 'destroyAscension'])->name('personajes.destroyascension')->middleware('auth.admin');

// Ruta para las noticias y sus comentarios
Route::resource('noticias', PostController::class);
Route::post('/comentario/store', [CommentController::class, 'store'])->name('comentario.store');
Route::post('/respuesta/store', [CommentController::class, 'replyStore'])->name('respuesta.store');
Route::delete('/comentario/destroy/{comentario}', [CommentController::class, 'destroy'])->name('comentario.destroy');

app/Models/Personaje.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Personaje extends Model
{
    use HasFactory;
    protected $fillable = array('nombre', 'imagen', 'titulo', 'alianza', 'rareza', 'arma', 'elemento', 'cumple',
    'constelacion', 'S_J', 'S_C', 'S_I', 'descripcion');

    public function materiales()
    {
        return $this->belongsToMany(Material::class);
    }

}

app/Http/Controllers/PersonajeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Personaje;
use App\Models\Material;
use App\Models\MaterialPersonaje;
use App\Http\Requests\StorePersonajeRequest;
use App\Http\Requests\StoreMaterialRequest;
use App\Http\Requests\StoreAscensionRequest;
use Illuminate\Support\Facades\Session;

class PersonajeController extends Controller
{
    // Agregamos seguridad, para que solo usuarios autenticados puedan acceder a las listas
    public function __construct()
    {
        //$this->middleware('auth')->except('create');
        $this->middleware('auth.admin')->except('index', 'listadoMateriales', 'listadoAscensiones', 'show', 'showMaterial');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $personajes = Personaje::All();

        return view('personajes.index')->with('personajes', $personajes);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('personajes.create')->with('personaje', new Personaje());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePersonajeRequest $request)
    {

        $datosvalidados = $request->validated();

        // Colocamos una imagen por defecto
        $datosvalidados['imagen'] = "imagenes/imagen_por_defecto.jpg";

        // Si recibe una imagen, cambiamos la imagen defecto por la imagen recibida, y la guardamos en storage
        if ($request->file('imagen')){
            $imagen = $request->file('imagen');
            $ruta = $imagen->store('imagenes', 'public');
     
            $datosvalidados['imagen'] = $ruta;
        }

        // Creamos el personaje con todos los datos
        Personaje::create($datosvalidados);

        // Mostramos mensaje.
        Session::flash('mensaje', 'Personaje creado correctamente.');
        Session::flash('alert-class', 'alert-success');

        return redirect()->route('personajes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Personaje $personaje)
    {
        // Conseguimos la informacion del personaje
        return view('personajes.personaje')->with('personaje', $personaje);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Personaje $personaje)
    {
        return view('personajes.edit')->with('personaje', $personaje);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StorePersonajeRequest $request, Personaje $personaje)
    {
        $datosvalidados = $request->validated();

        if ($request->file('imagen')){
            // Borramos la imagen anterior, siempre y cuando esta no sea la imagen que configuramos por defecto
            if($personaje->imagen != 'imagenes/imagen_por_defecto.jpg') { unlink(storage_path('app/public/'.$personaje->imagen)); }

            $imagen = $request->file('imagen');
            $ruta = $imagen->store('imagenes', 'public');
     
            $datosvalidados['imagen'] = $ruta;
        }

        // Actualizamos el personaje.
        $personaje->update($datosvalidados);

        // Mostramos un mensaje.
        Session::flash('mensaje', 'Personaje actualizado correctamente.');
        Session::flash('alert-class', 'alert-success');

        // Redireccionamos al index.
        return redirect()->route('personajes.show',$personaje);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Personaje $personaje)
    {
        // Borramos la imagen del servidor, siempre y cuando esta no sea la imagen que configuramos por defecto
        if($personaje->imagen != 'imagenes/imagen_por_defecto.jpg') { unlink(storage_path('app/public/'.$personaje->imagen)); }

        // Borramos el registro
        $personaje->delete();

        // Mostramos mensaje
        Session::flash('mensaje', 'Personaje borrado correctamente.');
        Session::flash('alert-class', 'alert-success');

        // Redireccionamos al index
        return redirect()->route('personajes.index');
    }

    //////////////////////////////
    // FUNCIONES PARA LOS MATERIALES
    //////////////////////////////

    public function listadoMateriales()
    {
        $materiales = Material::All();

        return view('personajes.listaMateriales')->with('materiales', $materiales);
    }

    public function createMaterial()
    {
        return view('personajes.createMaterial')->with('material', new Material());
    }

    public function storeMaterial(StoreMaterialRequest $request)
    {
        $datosvalidados = $request->validated();
        $datosvalidados['imagen'] = "imagenes/imagen_por_defecto.jpg";

        if ($request->file('imagen')){
            $imagen = $request->file('imagen');
            $ruta = $imagen->store('imagenes', 'public');
     
            $datosvalidados['imagen'] = $ruta;
        }

        // Creamos el personaje con todos los datos
        Material::create($datosvalidados);

        // Mostramos mensaje.
        Session::flash('mensaje', 'Material creado correctamente.');
        Session::flash('alert-class', 'alert-success');

        return redirect()->route('personajes.listadomateriales');
    }

    public function showMaterial(Material $material)
    {
        // Conseguimos la informacion del material
        return view('personajes.material')->with('material', $material);
    }

    public function editMaterial(Material $material)
    {
        return view('personajes.editMaterial')->with('material', $material);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function updateMaterial(StoreMaterialRequest $request, Material $material)
    {
        $datosvalidados = $request->validated();

        if ($request->file('imagen')){
            // Borramos la imagen anterior, siempre y cuando no sea la imagen por defecto
            if($material->imagen != 'imagenes/imagen_por_defecto.jpg') { unlink(storage_path('app/public/'.$material->imagen)); }

            $imagen = $request->file('imagen');
            $ruta = $imagen->store('imagenes', 'public');
     
            $datosvalidados['imagen'] = $ruta;
        }

        // Actualizamos el material.
        $material->update($datosvalidados);

        // Mostramos un mensaje.
        Session::flash('mensaje', 'Material actualizado correctamente.');
        Session::flash('alert-class', 'alert-success');

        // Redireccionamos al index.
        return redirect()->route('personajes.listadomateriales');
    }

    public function destroyMaterial(Material $material)
    {
        // Borramos la imagen siempre y cuando no sea la imagen por defecto
        if($material->imagen != 'imagenes/imagen_por_defecto.jpg') { unlink(storage_path('app/public/'.$material->imagen)); }

        // Borramos el registro
        $material->delete();

        // Mostramos mensaje
        Session::flash('mensaje', 'Material borrado correctamente.');
        Session::flash('alert-class', 'alert-success');

        // Redireccionamos al index
        return redirect()->route('personajes.listadomateriales');
    }

     //////////////////////////////
    // FUNCIONES PARA LAS ASCENSIONES
    //////////////////////////////

    public function listadoAscensiones()
    {
        $ascensiones = MaterialPersonaje::All();
        $personajes = Personaje::All();
        $materiales = Material::All();

        return view('personajes.listaAscensiones')->with('materiales',$materiales)->with('ascensiones', $ascensiones)->with('personajes', $personajes);
    }

    public function createAscension()
    {
        $materiales = Material::all();
        $personajes = Personaje::all();
        return view('personajes.createAscension')->with('materiales', $materiales)->with('personajes', $personajes)->with('ascension', new MaterialPersonaje());
    }

    public function storeAscension(StoreAscensionRequest $request)
    {

        // Creamos el personaje con todos los datos
        MaterialPersonaje::create( $request->validated());

        // Mostramos mensaje.
        Session::flash('mensaje', 'Ascensión creada correctamente.');
        Session::flash('alert-class', 'alert-success');

        return redirect()->route('personajes.listadoascensiones');
    }

    public function editAscension(MaterialPersonaje $ascension)
    {
        $materiales = Material::all();
        $personajes = Personaje::all();
        return view('personajes.editAscension')->with('materiales', $materiales)->with('personajes', $personajes)->with('ascension', $ascension);
    }

    public function updateAscension(StoreAscensionRequest $request, MaterialPersonaje $ascension)
    {
        // Actualizamos la ascensión.
        $ascension->update($request->validated());

        // Guardamos un mensaje.
        Session::flash('mensaje', 'Ascensión actualizada correctamente.');
        Session::flash('alert-class', 'alert-success');

        // Redireccionamos al listado de ascensiones.
        return redirect()->route('personajes.listadoascensiones');
    }

    public function destroyAscension(MaterialPersonaje $ascension)
    {
       // Borramos el registro
        $ascension->delete();

        // guardamos mensaje

resources/views/personajes/_form.blade.php
@csrf
<table class="table">
    <tr>
        <td><label for="nombre" class="form-label">Nombre del personaje:</label></td>
        <td>
            <input type="text" class="form-control" id="nombre" name="nombre" value="{{ old('nombre',$personaje->nombre) }}" maxlength="30">
            @error('nombre')
            <small class='alert alert-danger'>{{ $message }}</small>
            @enderror
        </td>
    </tr>

    <tr>
        <td><label for="imagen" class="form-label">Imagen:</label> </td>
        <td>
            <i>Nueva imagen:</i><br/> <input type="file" class="form-control mb-3" id="imagen" name="imagen" value="{{ old('imagen',$personaje->imagen) }}" >
            @if (old('imagen',$personaje->imagen)) <!-- Si existe imagen anterior, se muestra  -->
                <i >Imagen anterior:</i><br/> <img style="margin-bottom:10px;" src='{{ URL::asset("storage/$personaje->imagen") }}' HEIGHT="100px" /> 
            @endif
            @if ($errors->has('imagen'))
            <small class='alert alert-danger'>{{ $errors->first('imagen') }}</small>
            @endif
        </td>
    </tr>

    <tr>
        <td><label for="titulo" class="form-label">Título:</label></td>
        <td>
            <input type="text" class="form-control" id="titulo" name="titulo" value="{{ old('titulo',$personaje->titulo) }}" maxlength="50">
            @error('titulo')
            <small class='alert alert-danger'>{{ $message }}</small>
            @enderror
        </td>
    </tr>

    <tr>
        <td><label for="alianza" class="form-label">Alianza:</label></td>
        <td>
            <input type="text" class="form-control" id="alianza" name="alianza" value="{{ old('alianza',$personaje->alianza) }}" maxlength="50">
            @error('alianza')
            <small class='alert alert-danger'>{{ $message }}</small>
            @enderror
        </td>
    </tr>
    <tr>
        <td><label for="rareza" class="form-label">Rareza:</label></td>
        <td>
            <input type="text" class="form-control" id="rareza" name="rareza" value="{{ old('rareza',$personaje->rareza) }}" maxlength="30">
            @error('rareza')
            <small class='alert alert-danger'>{{ $message }}</small>
            @enderror
        </td>
    </tr>
    <tr>
        <td><label for="arma" class="form-label">Arma:</label></td>
        <td>
            <input type="text" class="form-control" id="arma" name="arma" value="{{ old('arma',$personaje->arma) }}" maxlength="10">
            @error('arma')
            <small class='alert alert-danger'>{{ $message }}</small>
            @enderror
        </td>
    </tr>
    <tr>
        <td><label for="elemento" class="form-label">Elemento:</label></td>
        <td>
            <input type="text" class="form-control" id="elemento" name="elemento" value="{{ old('elemento',$personaje->elemento) }}" maxlength="10">
            @error('elemento')
            <small class='alert alert-danger'>{{ $message }}</small>
            @enderror
        </td>
    </tr>
    <tr>
        <td><label for="cumple" class="form-label">Día de nacimiento:</label></td>
        <td>
            <input type="text" class="form-control" id="cumple" name="cumple" value="{{ old('cumple',$personaje->cumple) }}" maxlength="30">
            @error('cumple')
            <small class='alert alert-danger'>{{ $message }}</small>
            @enderror
        </td>
    </tr>
    <tr>
        <td><label for="constelacion" class="form-label">Constelación:</label></td>
        <td>
            <input type="text" class="form-control" id="constelacion" name="constelacion" value="{{ old('constelacion',$personaje->constelacion) }}" maxlength="30">
            @error('constelacion')
            <small class='alert alert-danger'>{{ $message }}</small>
            @enderror
        </td>
    </tr>
    <tr>
        <td><label for="S_J" class="form-label">Seiyuu en japonés:</label></td>
        <td>
            <input type="text" class="form-control" id="S_J" name="S_J" value="{{ old('S_J',$personaje->S_J) }}" maxlength="30">
            @error('S_J')
            <small class='alert alert-danger'>{{ $message }}</small>
            @enderror
        </td>
    </tr>
    <tr>
        <td><label for="S_C" class="form-label">Seiyuu en chino:</label></td>
        <td>
            <input type="text" class="form-control" id="S_C" name="S_C" value="{{ old('S_C',$personaje->S_C) }}" maxlength="30">
            @error('S_C')
            <small class='alert alert-danger'>{{ $message }}</small>
            @enderror
        </td>
    </tr>
    <tr>
        <td><label for="S_I" class="form-label">Seiyuu en inglés:</label></td>
        <td>
            <input type="text" class="form-control" id="S_I" name="S_I" value="{{ old('S_I',$personaje->S_I) }}" maxlength="30">
            @error('S_I')
            <small class='alert alert-danger'>{{ $message }}</small>
            @enderror
        </td>
    </tr>
    <tr>
        <td><label for="descripcion" class="form-label">Descripción:</label><br></td>
        <td>
            <textarea class="form-control" name="descripcion" id="descripcion" rows="10" cols="50" maxlength="200">{{ old('descripcion',$personaje->descripcion) }}</textarea>
            @error('descripcion')
            <small class='alert alert-danger'>{{ $message }}</small>
            @enderror
        </td>
    </tr>
</table>

resources/views/personajes/_formAscension.blade.php
@csrf
<div class="mb-3">
    <label for="material_id" class="form-label">ID del material</label> 
    <select name="material_id" id="material_id" class="form-control">
        <option value="0">ID del material:</option>
        @foreach ($materiales as $material)
            <option value="{{  $material->id }}" @if ($material->id === old('material_id',$ascension->material_id) ) selected @endif>{{ $material->id }} - {{ $material->nombre }}</option>
        @endforeach
    </select>
    @error('material_id')
    <small class="alert alert-danger">{{ $message }}</small>
    @enderror
</div>

<div class="mb-3">
    <label for="personaje_id" class="form-label">ID del personaje</label>
    <select name="personaje_id" id="personaje_id" class="form-control">
        <option value="0">ID del personaje:</option>
        @foreach ($personajes as $personaje)
            <option value="{{  $personaje->id }}"  @if ($personaje->id === old('personaje_id',$ascension->personaje_id) ) selected @endif>{{ $personaje->id }} - {{ $personaje->nombre }}</option>
        @endforeach
    </select>
    @error('personaje_id')
    <small class="alert alert-danger">{{ $message }}</small>
    @enderror
</div>

<div class="mb-3">
    <label for="oro" class="form-label">Oro requerido:</label>
    <input class="form-control" type="number" name="oro" id="oro" max="999999" value="{{ old('oro',$ascension->oro) }}">
    @error('oro')
    <small class="alert alert-danger">{{ $message }}</small>
    @enderror
</div>

<div class="mb-3">
    <label for="cantidad" class="form-label">Cantidad requerida:</label>
    <input class="form-control" type="number" name="cantidad" id="cantidad" max="999999"  value="{{ old('cantidad',$ascension->cantidad) }}">
    @error('cantidad')
    <small class="alert alert-danger">{{ $message }}</small>
    @enderror
</div>

resources/views/personajes/create.blade.php
@extends('plantillas.master')

@section('title')
Creación de personaje
@stop

@section('central')
<h2>CREACIÓN DE PERSONAJE</h2>
<form action="{{ route('personajes.store') }}" method="post" enctype="multipart/form-data">
    @include('personajes._form')
    <div style="text-align: right; margin-top: 10px;">
        <a class="btn btn-secondary" href="{{ route('personajes.index') }}">Cancelar</a>
        <input type="reset" class="btn btn-danger" name="Limpiar" />
        <input type="submit" class="btn btn-success" value="Crear personaje" />
    </div>
</form>
@stop

resources/views/personajes/createAscension.blade.php
@extends('plantillas.master')

@section('title')
Crear ascensión
@stop

@section('central')
<h2>Crear ascensión</h2>
<form action="{{ route('personajes.storeascension') }}" method="post">
    @include('personajes._formAscension')
    <div style="text-align: right; margin-top: 10px;">
        <a class="btn btn-secondary" href="{{ route('personajes.listadoascensiones') }}">Cancelar</a>
        <input type="reset" class="btn btn-danger" name="Limpiar" />
        <input type="submit" class="btn btn-success" value="Crear ascensión" />
    </div>
</form>

@stop

resources/views/personajes/createMaterial.blade.php
@extends('plantillas.master')

@section('title')
Creación de material
@stop

@section('central')
<h2>CREACIÓN DE MATERIAL</h2>
@if(Session::has('mensaje'))
<div class="alert {{ Session::get('alert-class') }}">
    {{ Session::get('mensaje') }}
</div>
@endif
<form action="{{ route('personajes.storematerial') }}" method="post" enctype="multipart/form-data">
    @include('personajes._formMaterial')
    <div style="text-align: right; margin-top: 10px;">
        <a class="btn btn-secondary" href="{{ route('personajes.listadomateriales') }}">Cancelar</a>
        <input type="reset" class="btn btn-danger" name="Limpiar" />
        <input type="submit" class="btn btn-success" value="Crear material" />
    </div>
</form>
@stop

resources/views/personajes/edit.blade.php
@extends('plantillas.master')

@section('title')
Edición de personaje
@stop

@section('central')
<h2>EDICIÓN DE PERSONAJE</h2>

<form action="{{ route('personajes.update', $personaje->id) }}" method="post" enctype="multipart/form-data">
    @METHOD('PUT')
    @include('personajes._form')
    <div style="text-align: right; margin-top: 10px;">
        <a class="btn btn-secondary" href="{{ route('personajes.show', $personaje) }}">Cancelar</a>
        <input type="reset" class="btn btn-danger" name="Limpiar" />
        <input type="submit" class="btn btn-success" value="Guardar cambios" />
    </div>
</form>
@stop

resources/views/personajes/personaje.blade.php
@extends('plantillas.master')

@section('title')
{{ $personaje->nombre }}
@stop

@section('central')

<!-- Se o usuario está rexistrado e é admin móstranse opcións -->
@auth
@if (auth()->user()->role == "admin")
<div class="btnDerecha">
<a href="{{ route('personajes.edit',$personaje) }}" class="btn btn-warning" title="Editar este personaje."><i class="fas fa-edit"></i></a> 
<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#ModalBorrar" title="Borrar este personaje."><i class="fas fa-trash"></i></button>
</div>
@endif
@endauth

<!-- Tabla que mostra os datos -->
<div class="container">
    <div class="row">
        <div class="bg-dark text-white" style="font-size:18px; padding:5px; font-weight: bold;">{{ $personaje->nombre }}</div>
    </div>

    <div class="row">
        <div class="text-center col" style="margin-top:2px;"><center><img src='{{ URL::asset("storage/$personaje->imagen") }}' width="180" /></center></div>
        <div class="col-12 col-xl-9">
            <div class="row">
                <div class="row d-flex flex-row bd-highlight filaInfo">
                    <div class="col-12 col-md-3 bg-secondary text-white fw-bolder" style="padding:10px;">Título</div>
                    <div class="col-12 col-md-9" style="padding:10px;">{{ $personaje->titulo }}</div>
                </div>
                <div class="row d-flex flex-row bd-highlight filaInfo">
                    <div class="col-md-3 bg-secondary text-white fw-bolder" style="padding:10px;">Alianza</div>
                    <div  class="col-12 col-md-9" style="padding:10px;">{{ $personaje->alianza }}</div>
                </div>
                <div class="row d-flex flex-row bd-highlight filaInfo">
                    <div class="col-md-3 bg-secondary text-white fw-bolder" style="padding:10px;">Rareza</div>
                    <div  class="col-12 col-md-9" style="padding:10px;">{{ $personaje->rareza }}</div>
                </div>
                <div class="row d-flex flex-row bd-highlight filaInfo">
                    <div class="col-md-3 bg-secondary text-white fw-bolder" style="padding:10px;">Arma</div>
                    <div  class="col-12 col-md-9" style="padding:10px;">{{ $personaje->arma }}</div>
                </div>
                <div class="row d-flex flex-row bd-highlight filaInfo">
                    <div class="col-md-3 bg-secondary text-white fw-bolder" style="padding:10px;">Elemento</div>
                    <div  class="col-12 col-md-9" style="padding:10px;">{{ $personaje->elemento }}</div>
                </div>
                <div class="row d-flex flex-row bd-highlight filaInfo">
                    <div class="col-md-3 bg-secondary text-white fw-bolder" style="padding:10px;">Día de nacimiento</div>
                    <div  class="col-12 col-md-9" style="padding:10px;">{{ $personaje->cumple }}</div>
                </div>
                <div class="row d-flex flex-row bd-highlight filaInfo">
                    <div class="col-md-3 bg-secondary text-white fw-bolder" style="padding:10px;">Constelación</div>
                    <div  class="col-12 col-md-9" style="padding:10px;">{{ $personaje->constelacion }}</div>
                </div>
                <div class="row d-flex flex-row bd-highlight filaInfo">
                    <div class="col-md-3 bg-secondary text-white fw-bolder" style="padding:10px;">Seiyuu en japonés</div>
                    <div  class="col-12 col-md-9" style="padding:10px;">{{ $personaje->S_J }}</div>
                </div>
                <div class="row d-flex flex-row bd-highlight filaInfo">
                    <div class="col-md-3 bg-secondary text-white fw-bolder" style="padding:10px;">Seiyuu en chino</div>
                    <div  class="col-12 col-md-9" style="padding:10px;">{{ $personaje->S_C }}</div>
                </div>
                <div class="row d-flex flex-row bd-highlight filaInfo">
                    <div class="col-md-3 bg-secondary text-white fw-bolder" style="padding:10px;">Seiyuu en inglés</div>
                    <div  class="col-12 col-md-9" style="padding:10px;">{{ $personaje->S_I }}</div>
                </div>
                <div class="row d-flex flex-row bd-highlight filaInfo">
                    <div class="col-md-3 bg-secondary text-white fw-bolder" style="padding:10px;">Descripción</div>
                    <div  class="col-12 col-md-9" style="padding:10px;">{{ $personaje->descripcion }}</div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal para borrar -->
<div class="modal fade" id="ModalBorrar" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Borrar</h5>
        </button>
      </div>
      <div class="modal-body">
        ¿Desea realmente borrar este personaje?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <form action="{{ route('personajes.destroy',$personaje) }}" method="post">@csrf @method('DELETE') <input type="submit" class="btn btn-danger" value="Borrar" /> </form>      </div>
    </div>
  </div>
</div>

@stop